brivo/brewery/urls.py
from django.urls import path

from . import views

app_name = "brewery"
urlpatterns = [
    # Fermentables
    path('fermentable', views.FermentableListView.as_view(),
         name='fermentable-list'),
    path('fermentable/create', views.FermentableCreateView.as_view(),
         name='fermentable-create'),
    path('fermentable/<int:pk>', views.FermentableDetailView.as_view(),
         name='fermentable-detail'),
    path('fermentable/<int:pk>/update', views.FermentableUpdateView.as_view(),
         name='fermentable-update'),
    path('fermentable/<int:pk>/delete', views.FermentableDeleteView.as_view(),
         name='fermentable-delete'),
    path(
        r'fermentable/autocomplete',
        views.FermentableAutocomplete.as_view(),
        name='fermentable-autocomplete',
    ),

    # Hops
    path('hop', views.HopListView.as_view(),
         name='hop-list'),
    path('hop/create', views.HopCreateView.as_view(),
         name='hop-create'),
    path('hop/<int:pk>', views.HopDetailView.as_view(),
         name='hop-detail'),
    path('hop/<int:pk>/update', views.HopUpdateView.as_view(),
         name='hop-update'),
    path('hop/<int:pk>/delete', views.HopDeleteView.as_view(),
         name='hop-delete'),
    path(
        r'hop/autocomplete',
        views.HopAutocomplete.as_view(),
        name='hop-autocomplete',
    ),

    # Yeasts
    path('yeast', views.YeastListView.as_view(),
         name='yeast-list'),
    path('yeast/create', views.YeastCreateView.as_view(),
         name='yeast-create'),
    path('yeast/<int:pk>', views.YeastDetailView.as_view(),
         name='yeast-detail'),
    path('yeast/<int:pk>/update', views.YeastUpdateView.as_view(),
         name='yeast-update'),
    path('yeast/<int:pk>/delete', views.YeastDeleteView.as_view(),
         name='yeast-delete'),
    path(
        r'yeast/autocomplete',
        views.YeastAutocomplete.as_view(),
        name='yeast-autocomplete',
    ),

    # Extras
    path('extra', views.ExtraListView.as_view(),
         name='extra-list'),
    path('extra/create', views.ExtraCreateView.as_view(),
         name='extra-create'),
    path('extra/<int:pk>', views.ExtraDetailView.as_view(),
         name='extra-detail'),
    path('extra/<int:pk>/update', views.ExtraUpdateView.as_view(),
         name='extra-update'),
    path('extra/<int:pk>/delete', views.ExtraDeleteView.as_view(),
         name='extra-delete'),
    path(
        r'extra/autocomplete',
        views.ExtraAutocomplete.as_view(),
        name='extra-autocomplete',
    ),

    # Styles
    path('style', views.StyleListView.as_view(),
         name='style-list'),
    path('style/create', views.StyleCreateView.as_view(),
         name='style-create'),
    path('style/<int:pk>', views.StyleDetailView.as_view(),
         name='style-detail'),
    path('style/<int:pk>/update', views.StyleUpdateView.as_view(),
         name='style-update'),
    path('style/<int:pk>/delete', views.StyleDeleteView.as_view(),
         name='style-delete'),
    path('style/<int:pk>/info', views.StyleInfoView.as_view(),
         name='style-info'),


    # Recipes
    path('recipe', views.RecipeListView.as_view(),
         name='recipe-list'),
    path('recipe/create', views.RecipeCreateView.as_view(),
         name='recipe-create'),
    path('recipe/<int:pk>', views.RecipeDetailView.as_view(),
         name='recipe-detail'),
    path('recipe/<int:pk>/print', views.RecipePrintView.as_view(),
         name='recipe-print'),
    path('recipe/<int:pk>/update', views.RecipeUpdateView.as_view(),
         name='recipe-update'),
    path('recipe/<int:pk>/delete', views.RecipeDeleteView.as_view(),
         name='recipe-delete'),
    path(
        r'recipe/info',
        views.get_recipe_data,
        name='recipe-info',
    ),
    path('recipe/import', views.RecipeImportView.as_view(),
         name='recipe-import'),

    # Batches
    path('batch', views.BatchListView.as_view(),
         name='batch-list'),
    path('batch/<int:pk>', views.BatchDetailView.as_view(),
         name='batch-detail'),
    path('batch/create', views.BatchView.as_view(),
         name='batch-create'),
    path('batch/<int:pk>/update', views.BatchView.as_view(),
         name='batch-update'),
    path('batch/<int:pk>/delete', views.BatchDeleteView.as_view(),
         name='batch-delete'),
    path('batch/import', views.BatchImportView.as_view(),
         name='batch-import'),
    path('batch/<int:batch_pk>/fermentation_check', views.FermentationCheckCreateView.as_view(),
         name='batch-fermentation_check-create'),
    path('batch/<int:batch_pk>/fermentation_check/<int:pk>/update', views.FermentationCheckUpdateView.as_view(),
         name='batch-fermentation_check-update'),
    path('batch/<int:batch_pk>/fermentation_check/<int:pk>/delete', views.FermentationCheckDeleteView.as_view(),
         name='batch-fermentation_check-delete'),
]

brivo/users/urls.py
from django.urls import path
from django.views import defaults as default_views

from brivo.users.views import (
    user_redirect_view,
    user_settings_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("<str:username>/", view=user_settings_view, name="settings"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.utils import translation
from django.urls import include, path, re_path
from django.conf.urls.i18n import i18n_patterns
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from brivo.users.api.views import CustomLogoutView

def set_language_from_url(request, user_language):
    translation.activate(user_language)
    request.session[translation.LANGUAGE_SESSION_KEY] = user_language
    return redirect(request.META.get('HTTP_REFERER'))

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management

    re_path(r'^celery-progress/', include('celery_progress.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router", namespace="api")),
    path("api/auth/logout/", CustomLogoutView.as_view()),
    path('api/auth/', include('dj_rest_auth.urls')),
    path('api/auth/registration/', include('dj_rest_auth.registration.urls')),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
        path(r'/set_language/(?P<user_language>\w+)/$', set_language_from_url, name="set_language_from_url"),
        path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
        path(
            "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
        ),
        path("users/", include("brivo.users.urls", namespace="users")),
        path("brewery/", include("brivo.brewery.urls", namespace="brewery")),
        path("accounts/email/", default_views.page_not_found, name="account_email", kwargs={"exception": Exception("Page not Found")},),
        path("accounts/", include("allauth.urls")),
    )


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

brivo/brewery/models/inventory.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from brivo.brewery.models import BaseModel

__all__ = ("Inventory",)

class Inventory(models.Model):
    user = models.OneToOneField("users.User", verbose_name=_("brewery.User"), on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.user.username} Inventory"

brivo/users/forms.py
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.safestring import mark_safe
from string import Template
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from allauth.account.forms import SignupForm

from brivo.users.models import (
    GENERAL_UNITS,
    GRAVITY_UNITS,
    UserProfile,
    UserBrewery)


User = get_user_model()


class AdminUserCreationForm(admin_forms.UserCreationForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)


    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ('email', 'username')
        error_messages = {
            "email": {"unique": _("This email has already been registered.")},
            "username": {"unique": _("This username has already been taken.")},
        }

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        profile = UserProfile.objects.create(user=user).save()
        brewery_profile = UserBrewery.objects.create(user=user).save()
        if commit:
            user.save()
        return user


class AdminUserChangeForm(admin_forms.UserChangeForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta(admin_forms.UserChangeForm.Meta):
        model = User
        fields = ('username', 'email', 'password', 'is_active', 'is_staff')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class BrivoSignupForm(SignupForm):

    general_units = forms.ChoiceField(choices=GENERAL_UNITS, required=False)
    gravity_units = forms.ChoiceField(choices=GRAVITY_UNITS, required=False)

    # Override the init method
    def __init__(self, *args, **kwargs):
        # Call the init of the parent class
        super().__init__(*args, **kwargs)

    # Put in custom signup logic
    def custom_signup(self, request, user):
        print("Setting data")
        user.profile = UserProfile.objects.create(user=user)
        user.profile.general_units = self.cleaned_data["general_units"]
        user.profile.gravity_units = self.cleaned_data["gravity_units"]
        user.brewery_profile = UserBrewery.objects.create(user=user)
        user.brewery_profile.save()
        user.profile.save()
        user.save()


class ImagePreviewWidget(forms.widgets.FileInput):
    def render(self, name, value, attrs=None, **kwargs):
        input_html = super().render(name, value, attrs=None, **kwargs)
        if value:
            img_html = mark_safe(f'<br><br><img style="width: 200px; height: 200px;" class="img-thumbnail" src="/media/{value}"/>')
            return f'{img_html}{input_html}'
        else:
            return input_html


class UserForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """

    class Meta:
        model = User
        fields = ('username', 'email',)


class UserProfileForm(forms.ModelForm):
    image = forms.ImageField(widget=ImagePreviewWidget)
    class Meta:
        model = UserProfile
        fields = (
            "image",
            "general_units",
            "temperature_units",
            "gravity_units",
            "color_units",
        )

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = False


class UserBreweryForm(forms.ModelForm):
    image = forms.ImageField(widget=ImagePreviewWidget)
    class Meta:
        model = UserBrewery
        fields = (
            "image",
            "name",
            "external_link",
            "number_of_batches"
        )

    def __init__(self, *args, **kwargs):
        super(UserBreweryForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = False

brivo/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet
from rest_framework.permissions import IsAuthenticated
from dj_rest_auth.views import LogoutView

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)


class CustomLogoutView(LogoutView):
    permission_classes = (IsAuthenticated,)

brivo/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.base import ContextMixin, TemplateResponseMixin
from django.views.generic.edit import ProcessFormView
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.http.response import HttpResponseRedirect
from django.http import HttpResponseForbidden
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from brivo.users.models import UserProfile, UserBrewery
from brivo.users import forms

User = get_user_model()

def user_settings_view(request, username):
    if not request.user.is_authenticated:
        return render(request, "403.html")
    if username != request.user.username:
        return render(request, "404.html")
    user = request.user
    user_profile = user.profile
    user_brewery = user.brewery_profile
    user_form = forms.UserForm(instance=request.user)
    

    if request.method == "POST":
        if 'profile_form' in request.POST:
            profile_form = forms.UserProfileForm(request.POST, request.FILES, instance=user.profile)
            if profile_form.is_valid():
                profile_form.save()

        if 'user_form' in request.POST:
            user_form = forms.UserForm(request.POST, instance=request.user)
            if user_form.is_valid():
                user_form.save()

        if 'brewery_form' in request.POST:
            brewery_form = forms.UserBreweryForm(request.POST, request.FILES, instance=user.brewery_profile)
            if brewery_form.is_valid():
                brewery_form.save()

    if user_profile:
        profile_form = forms.UserProfileForm(instance=user_profile)
    else:
        profile_form = forms.UserProfileForm()
    if user_brewery:
        brewery_form = forms.UserBreweryForm(instance=user_brewery)
    else:
        brewery_form = forms.UserBreweryForm()
    return render(request, 'users/settings.html', {
        'profile_form': profile_form,
        'user_form': user_form,
        'brewery_form': brewery_form
    })


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:settings", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

brivo/templates/brewery/recipe/delete.html
{% load static %}
{% load widget_tweaks %}
{% load i18n %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{% trans "Delete Recipe" %}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">{% trans "Are you sure you want to delete recipe with name" %}
      <strong>{{ recipe.name }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">{% trans "Delete" %}</button>
  </div>

</form>
{% endblock content %}

brivo/templates/brewery/recipe/extra_formset.html
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}


<table class="table">
{{ formset.management_form|crispy }}
    <thead>
        <tr >
            <th class="text-center" scope="col">{% trans "Name" %}</th>
            <th class="text-center" scope="col">{% trans "Type" %}</th>
            <th class="text-center" scope="col">{% trans "Use" %}</th>
            <th class="text-center" scope="col">{% trans "Amount" %}</th>
            <th class="text-center" scope="col">{% trans "Time" %}</th>
            <th class="text-center" scope="col">{% trans "Action" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for form in formset.forms %}
            {{ form.media }}
            <tr class="{% cycle 'row1' 'row2' 'row3' 'row4' 'row5' %} formset_row-{{ formset.prefix }}">
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                <td>
                    {{ field.name.errors.as_ul }}
                    {{ form.name|as_crispy_field }}
                </td>
                <td>{{ field.type.errors.as_ul }}{{ form.type|as_crispy_field }}</td>
                <td>{{ field.use.errors.as_ul }}{{ form.use|as_crispy_field }}</td>
                <td>{{ field.amount.errors.as_ul }}{{ form.amount|as_crispy_field }}</td>
                <td>{{ field.time.errors.as_ul }}{{ form.time|as_crispy_field }}{{ form.time_unit|as_crispy_field }}</td>
                <td class="delet-row">{{ form.DELETE }}</td>
            </tr>
        {% endfor %}
</table>

<br>
<script src="{% static "js/jquery.formset.js" %}"></script>
<script src="{% static "js/jquery.autocomplete.js" %}"></script>
<script type="text/javascript">
$(function() {
    $('.formset_row-{{ formset.prefix }}').formset({
        addText: '<button type="button" class="add-extra btn btn-sm btn-warning"><span class="fa fa-plus"></span> Add extra</button>',
        deleteText: '<button type="button" class="delete-extra btn btn-sm btn-danger"><span class="fa fa-trash"></span></button>',
        prefix: '{{ formset.prefix }}',
        {% if formset.request.method == "GET" %} hideLastAddForm: true, {% endif %} 
        addCssClass: '{{ formset.prefix }}-add-row',          // CSS class applied to the add link
        deleteCssClass: '{{ formset.prefix }}-delete-row',    // CSS class applied to the delete link
        formCssClass: '{{ formset.prefix }}-dynamic-form', 
        added: function(row) {
            let row_index = row.find("input[id$=name]").prop("id").split("-")[1];
            $('#id_extras-' + row_index + '-name').autocomplete({
                serviceUrl: '{% url "brewery:extra-autocomplete" %}',
                noCache: false,
                minChars: 3,
                paramName: "q",
                width: '300',
                onSelect: function (suggestion) {
                    let row_index = row.find("input[id$=name]").prop("id").split("-")[1];
                    $('#id_extras-' + row_index + '-type').val(suggestion.data.type);
                    $('#id_extras-' + row_index + '-use').val(suggestion.data.use);
                }
            });
        }
    });

    $('#id_extras-0-name').autocomplete({
        serviceUrl: '{% url "brewery:extra-autocomplete" %}',
        noCache: false,
        minChars: 3,
        paramName: "q",
        width: '300',
        onSelect: function (suggestion) {
            $('#id_extras-0-type').val(suggestion.data.type);
            $('#id_extras-0-use').val(suggestion.data.use);
        }
    });
});
</script>

brivo/templates/brewery/recipe/import.html
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}

<form method="post" action="{% url 'brewery:recipe-import' %}" enctype="multipart/form-data">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{% trans "Import Recipe" %}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
      {{form|crispy}}
  </div>

  <div class="modal-footer">
    <button type="submit" id="import-btn" class="btn btn-primary">{% trans "Import" %}</button>
  </div>

</form>
{% endblock content %}

brivo/templates/brewery/recipe/list.html
{% extends "base.html" %}
{% load static %}
{% load brew_tags %}
{% load i18n %}

{% block title %}{% trans "Recipes" %}{% endblock title %}

{% block content %}
<h1 class="mt-3 mb-3">{% trans "Recipes" %}</h1>
<hl>
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog mt-5 modal-lg">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog mt-5 modal-lg" role="document">
    <div class="modal-content"></div>
  </div>
</div>
<div class="container">
    <div class="col-12 mb-3">
    {% if user.is_authenticated %}
    <a href="{% url 'brewery:recipe-create' %}"><button id="create-recipe" class="btn btn-success" type="button" name="button">
        <span class="fa fa-plus mr-2"></span>{% trans "Create Recipe" %}
    </button></a>
    <button id="import-recipe" class="bs-modal delete-recipe btn btn-primary" data-form-url="{% url 'brewery:recipe-import' %}" type="button" name="button">
        <span class="fa fa-file-import mr-2"></span>{% trans "Import Recipe" %}
    </button>
    {% endif %}
    <button id="toggle-filters" class="btn btn-primary" type="button" name="button" data-toggle="collapse" data-target="#filter-row" aria-expanded="false" aria-controls="collapseExample">
    {% trans "Toggle Filters" %}
    </button>
    </div>
    <div id="filter-row" class="row collapse">
        <div class="col">
            <div class="card card-body">
                <form method="get">
                    {{filter.form.as_p}}
                    <button class="btn btn-primary" name="button" type="submit"><span class="fa fa-filter mr-2"></span>{% trans "Filter" %}</button>
                </form>
            </div>
        </div>
    </div>
    <div id="progress-bar-wrapper" class="hidden" class='progress-wrapper'>
        <div id='progress-bar' class='progress-bar' style="background-color: #68a9ef; width: 0%;">&nbsp;</div>
        <div id="progress-bar-message"></div>
    </div>

<table id="recipes-table" class="table">
    <thead>
        <tr >
            <th class="text-center" scope="col">{% trans "Name" %}</th>
            <th class="text-center" scope="col">{% trans "Gravity" %} [{{user.profile.gravity_units}}]</th>
            <th class="text-center" scope="col">{% trans "ABV" %}</th>
            <th class="text-center" scope="col">{% trans "Size" %}</th>
            <th class="text-center" scope="col">{% trans "Style" %}</th>
            <th class="text-center" scope="col">{% trans "IBU" %}</th>
            <th class="text-center" scope="col">{% trans "Color" %} [{{user.profile.color_units}}]</th>
            <th class="text-center" scope="col">{% trans "Action" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for recipe in recipes %}
        <tr style="border-left-color:{{recipe.get_hex_color}};border-left-style:solid;border-left-width:10px">
            <td class="text-center" scope="row">{{recipe.name}}</td>
            <td class="text-center">{{recipe.get_gravity|get_obj_attr:user.profile.gravity_units|floatformat}}</td>
            <td class="text-center">{{recipe.get_abv|floatformat}}</td>
            <td class="text-center">{{recipe.expected_beer_volume|get_obj_attr:recipe.get_volume_unit|floatformat}}</td>
            <td class="text-center"><a class="bs-modal read-style" href="#" data-form-url="{% url 'brewery:style-detail' recipe.style.pk %}">{{recipe.style.name}}</a></td>
            <td class="text-center">{{recipe.get_ibu|floatformat}}</td>
            <td class="text-center">{{recipe.get_color|get_obj_attr:user.profile.color_units|floatformat}}</td>
            <td class="text-center">
                <!-- Read recipe buttons -->
                <button type="button" class="bs-modal read-recipe btn btn-sm btn-primary" data-form-url="{% url 'brewery:recipe-detail' recipe.pk %}">
                <span class="fa fa-eye"></span>
                </button>
                {% if user.is_authenticated %}
                <!-- Update recipe buttons -->
                <a href="{% url 'brewery:recipe-update' recipe.pk %}"><button type="button" class="update-recipe btn btn-sm btn-primary" data-form-url="{% url 'brewery:recipe-update' recipe.pk %}">
                <span class="fa fa-edit"></span>
                </button></a>
                <!-- Delete recipe buttons -->
                <button type="button" class="bs-modal delete-recipe btn btn-sm btn-danger" data-form-url="{% url 'brewery:recipe-delete' recipe.pk %}">
                <span class="fa fa-trash"></span>
                </button>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% if is_paginated %}
    {% include "pagination.html" %}
{% endif %}
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>
<script src="{% static 'celery_progress/celery_progress.js' %}"></script>
{% endblock content %}
{% block inline_javascript %}
<script defer type="text/javascript">
$(document).ready(function() {
    // Read and Delete book buttons open modal with id="modal"
    // The formURL is retrieved from the data of the element
    $(".bs-modal").each(function () {
        $(this).modalForm({formURL: $(this).data("form-url")});
    });

    // Hide message
    $(".alert").fadeTo(2000, 500).slideUp(500, function () {
        $(".alert").slideUp(500);
    });
  {% if messages %}
    {% for message in messages %}
        {% if message.extra_tags == "task_id" %}
            var progressUrl = "{% url 'celery_progress:task_status' message %}";
            CeleryProgressBar.initProgressBar(progressUrl, {
                onSuccess: function(progressBarElement, progressBarMessageElement, result){
                    result = this.getMessageDetails(result);
                    progressBarElement.style.backgroundColor = this.barColors.success;
                    progressBarMessageElement.textContent = "Uploaded " + result + " recipes.";
                    setTimeout(function () { 
                        location.reload();
                    }, 1 * 1000);
                },
            });
        {% endif %}
    {% endfor %}
  {% endif %}
});
</script>
{% endblock inline_javascript %}