brivo/brewery/urls.py
from django.urls import path

from . import views

app_name = "brewery"
urlpatterns = [
    # Fermentables
    path('fermentable', views.FermentableListView.as_view(),
         name='fermentable-list'),
    path('fermentable/create', views.FermentableCreateView.as_view(),
         name='fermentable-create'),
    path('fermentable/<int:pk>', views.FermentableDetailView.as_view(),
         name='fermentable-detail'),
    path('fermentable/<int:pk>/update', views.FermentableUpdateView.as_view(),
         name='fermentable-update'),
    path('fermentable/<int:pk>/delete', views.FermentableDeleteView.as_view(),
         name='fermentable-delete'),
    path(
        r'fermentable/autocomplete',
        views.FermentableAutocomplete.as_view(),
        name='fermentable-autocomplete',
    ),

    # Hops
    path('hop', views.HopListView.as_view(),
         name='hop-list'),
    path('hop/create', views.HopCreateView.as_view(),
         name='hop-create'),
    path('hop/<int:pk>', views.HopDetailView.as_view(),
         name='hop-detail'),
    path('hop/<int:pk>/update', views.HopUpdateView.as_view(),
         name='hop-update'),
    path('hop/<int:pk>/delete', views.HopDeleteView.as_view(),
         name='hop-delete'),
    path(
        r'hop/autocomplete',
        views.HopAutocomplete.as_view(),
        name='hop-autocomplete',
    ),

    # Yeasts
    path('yeast', views.YeastListView.as_view(),
         name='yeast-list'),
    path('yeast/create', views.YeastCreateView.as_view(),
         name='yeast-create'),
    path('yeast/<int:pk>', views.YeastDetailView.as_view(),
         name='yeast-detail'),
    path('yeast/<int:pk>/update', views.YeastUpdateView.as_view(),
         name='yeast-update'),
    path('yeast/<int:pk>/delete', views.YeastDeleteView.as_view(),
         name='yeast-delete'),
    path(
        r'yeast/autocomplete',
        views.YeastAutocomplete.as_view(),
        name='yeast-autocomplete',
    ),

    # Extras
    path('extra', views.ExtraListView.as_view(),
         name='extra-list'),
    path('extra/create', views.ExtraCreateView.as_view(),
         name='extra-create'),
    path('extra/<int:pk>', views.ExtraDetailView.as_view(),
         name='extra-detail'),
    path('extra/<int:pk>/update', views.ExtraUpdateView.as_view(),
         name='extra-update'),
    path('extra/<int:pk>/delete', views.ExtraDeleteView.as_view(),
         name='extra-delete'),
    path(
        r'extra/autocomplete',
        views.ExtraAutocomplete.as_view(),
        name='extra-autocomplete',
    ),

    # Styles
    path('style', views.StyleListView.as_view(),
         name='style-list'),
    path('style/create', views.StyleCreateView.as_view(),
         name='style-create'),
    path('style/<int:pk>', views.StyleDetailView.as_view(),
         name='style-detail'),
    path('style/<int:pk>/update', views.StyleUpdateView.as_view(),
         name='style-update'),
    path('style/<int:pk>/delete', views.StyleDeleteView.as_view(),
         name='style-delete'),
    path('style/<int:pk>/info', views.StyleInfoView.as_view(),
         name='style-info'),


    # Recipes
    path('recipe', views.RecipeListView.as_view(),
         name='recipe-list'),
    path('recipe/create', views.RecipeCreateView.as_view(),
         name='recipe-create'),
    path('recipe/<int:pk>', views.RecipeDetailView.as_view(),
         name='recipe-detail'),
    path('recipe/<int:pk>/print', views.RecipePrintView.as_view(),
         name='recipe-print'),
    path('recipe/<int:pk>/update', views.RecipeUpdateView.as_view(),
         name='recipe-update'),
    path('recipe/<int:pk>/delete', views.RecipeDeleteView.as_view(),
         name='recipe-delete'),
    path(
        r'recipe/info',
        views.get_recipe_data,
        name='recipe-info',
    ),
    path('recipe/import', views.RecipeImportView.as_view(),
         name='recipe-import'),

    # Batches
    path('batch', views.BatchListView.as_view(),
         name='batch-list'),
    path('batch/<int:pk>', views.BatchDetailView.as_view(),
         name='batch-detail'),
    path('batch/create', views.BatchView.as_view(),
         name='batch-create'),
    path('batch/<int:pk>/update', views.BatchView.as_view(),
         name='batch-update'),
    path('batch/<int:pk>/delete', views.BatchDeleteView.as_view(),
         name='batch-delete'),
    path('batch/import', views.BatchImportView.as_view(),
         name='batch-import'),
    path('batch/<int:batch_pk>/fermentation_check', views.FermentationCheckCreateView.as_view(),
         name='batch-fermentation_check-create'),
    path('batch/<int:batch_pk>/fermentation_check/<int:pk>/update', views.FermentationCheckUpdateView.as_view(),
         name='batch-fermentation_check-update'),
    path('batch/<int:batch_pk>/fermentation_check/<int:pk>/delete', views.FermentationCheckDeleteView.as_view(),
         name='batch-fermentation_check-delete'),
]

brivo/users/urls.py
from django.urls import path
from django.views import defaults as default_views

from brivo.users.views import (
    user_redirect_view,
    user_settings_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("<str:username>/", view=user_settings_view, name="settings"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.utils import translation
from django.urls import include, path, re_path
from django.conf.urls.i18n import i18n_patterns
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from brivo.users.api.views import CustomLogoutView

def set_language_from_url(request, user_language):
    translation.activate(user_language)
    request.session[translation.LANGUAGE_SESSION_KEY] = user_language
    return redirect(request.META.get('HTTP_REFERER'))

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management

    re_path(r'^celery-progress/', include('celery_progress.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router", namespace="api")),
    path("api/auth/logout/", CustomLogoutView.as_view()),
    path('api/auth/', include('dj_rest_auth.urls')),
    path('api/auth/registration/', include('dj_rest_auth.registration.urls')),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
        path(r'/set_language/(?P<user_language>\w+)/$', set_language_from_url, name="set_language_from_url"),
        path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
        path(
            "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
        ),
        path("users/", include("brivo.users.urls", namespace="users")),
        path("brewery/", include("brivo.brewery.urls", namespace="brewery")),
        path("accounts/email/", default_views.page_not_found, name="account_email", kwargs={"exception": Exception("Page not Found")},),
        path("accounts/", include("allauth.urls")),
    )


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

brivo/brewery/models/batch.py
import datetime

from django.db import models
from django.utils.translation import gettext_lazy as _


from brivo.brewery.models import BaseModel, VOLUME_UNITS
from brivo.utils.measures import BeerGravity
from brivo.brewery.fields import TemperatureField, BeerGravityField, VolumeField
from brivo.utils import functions

from modelcluster.fields import ParentalKey


__all__ = ("Batch", "FermentationCheck", "BATCH_STAGE_ORDER", "BATCH_STAGES", "SUGAR_TYPE")


BATCH_STAGES = (
    ("INIT", _("Init")),
    ("MASHING", _("Mashing")),
    ("BOIL", _("Boil")),
    ("PRIMARY_FERMENTATION", _("Primary Fermentation")),
    ("SECONDARY_FERMENTATION", _("Secondary Fermentation")),
    ("PACKAGING", _("Packaging")),
    ("FINISHED", _("Finished")),
)

BATCH_STAGE_ORDER = [bs[0] for bs in BATCH_STAGES]

CARBONATION_TYPE = (("FORCED", _("Forced")), ("REFERMENTATION", _("Refermentation")))
SUGAR_TYPE = (
    ("CORN_SUGAR", _("Corn Sugar")),
    ("TABLE_SUGAR", _("Table Sugar")),
    ("DRY_EXTRACT", _("Dry Extract"))
)

class FermentationCheck(BaseModel):
    batch = ParentalKey(
        "brewery.Batch",
        verbose_name=_("Batch"),
        on_delete=models.CASCADE,
        related_name="fermentation_checks",
    )
    sample_day = models.DateField(
        _("Sample Day"),
        null=True,
        auto_now=False,
        auto_now_add=False,
    )
    gravity = BeerGravityField(
        verbose_name=_("Gravity"), null=True
    )
    beer_temperature = TemperatureField(
        verbose_name=_("Beer Temperature"), null=True, blank=True
    )
    ambient_temperature = TemperatureField(
        verbose_name=_("Ambient Temperature"), null=True, blank=True
    )
    comment = models.TextField(_("Comment"), blank=True, null=True)


class Batch(BaseModel):
    # Operational fields
    stage = models.CharField(
        _("Stage"), max_length=50, choices=BATCH_STAGES, default="INIT"
    )
    recipe = ParentalKey("Recipe", verbose_name=_("Recipe"), on_delete=models.CASCADE)
    user = models.ForeignKey(
        "users.User", verbose_name=_("User"), on_delete=models.CASCADE
    )

    # Stage 1 fields: info and mashing
    # name - inherited from BaseModel
    batch_number = models.IntegerField(_("Batch Number"), null=True)
    brewing_day = models.DateField(
        _("Brewing Day"), auto_now=False, auto_now_add=False, null=True
    )
    grain_temperature = TemperatureField(
        verbose_name=_("Grain Temperature"), null=True, default=273.15 + 20
    )
    sparging_temperature = TemperatureField(
        verbose_name=_("Sparging Temperature"), null=True, default=273.15 + 78
    )

    # Stage 2 fields: boil
    gravity_before_boil = BeerGravityField(
        verbose_name=_("Gravity Before Boil"), null=True
    )

    # Stage 3 fields: primary fermentation
    initial_gravity = BeerGravityField(verbose_name=_("Initial Gravity"), null=True)
    wort_volume = VolumeField(
        verbose_name=_("Wort Volume"),
        null=True,
        unit_choices=VOLUME_UNITS,
    )
    boil_loss = VolumeField(
        verbose_name=_("Boil Waists"),
        null=True,
        unit_choices=VOLUME_UNITS,
    )
    primary_fermentation_temperature = TemperatureField(
        verbose_name=_("Primary Fermentation Temperature"), null=True, blank=True
    )
    primary_fermentation_start_day = models.DateField(
        _("Primary Fermentation Start Day"),
        null=True,
        auto_now=False,
        auto_now_add=False,
    )

    # Stage 4 fields: secondary fermentation
    secondary_fermentation_temperature = TemperatureField(
        verbose_name=_("Secondary Fermentation Temperature"), null=True, blank=True
    )
    secondary_fermentation_start_day = models.DateField(
        _("Secondary Fermentation Start Day"),
        null=True,
        blank=True,
        auto_now=False,
        auto_now_add=False,
    )
    dry_hops_start_day = models.DateField(
        _("Dry Hops Start Day"),
        null=True,
        blank=True,
        auto_now=False,
        auto_now_add=False,
    )
    post_primary_gravity = BeerGravityField(
        verbose_name=_("Post-primary Gravity"),
        null=True,
        blank=True,
    )

    # Stage 4 fields: packaging
    packaging_date = models.DateField(
        _("Packaging Start Day"), auto_now=False, auto_now_add=False, null=True
    )
    end_gravity = BeerGravityField(verbose_name=_("End Gravity"), null=True)
    beer_volume = VolumeField(
        verbose_name=_("Beer Volume"),
        null=True,
        unit_choices=VOLUME_UNITS,
    )
    carbonation_type = models.CharField(
        _("Carbonation Type"), max_length=50, choices=CARBONATION_TYPE, null=True
    )
    carbonation_level = models.DecimalField(
        _("Carbonation Level"), max_digits=5, decimal_places=2, null=True
    )
    sugar_type = models.CharField(
        _("Sugar Type"), max_length=50, choices=SUGAR_TYPE, null=True, blank=True
    )
    priming_temperature = TemperatureField(
        verbose_name=_("Priming Temperature"), null=True, blank=True
    )

    hidden_fields = ["stage"]

    def get_hex_color(self):
        return self.recipe.get_hex_color()

    def get_size_with_trub_loss(self):
        pass

    def get_actuall_mash_efficiency(self):
        try:
            vol = self.wort_volume.l + self.boil_loss.l
            grain_sugars = self.recipe.get_grain_sugars().kg * 100.0
            other_sugars = self.recipe.get_other_sugars().kg * 100.0
            grain_gravity = grain_sugars / (
                vol - grain_sugars / 145.0 + grain_sugars / 100.0
            )
            other_gravity = other_sugars / (
                vol - other_sugars / 145.0 + other_sugars / 100.0
            )
            max_gravity = BeerGravity(plato=(grain_gravity + other_gravity))
            return (
                (self.initial_gravity.plato * vol)
                / (max_gravity.plato * self.recipe.get_primary_volume().l)
            ) * 100.0
        except AttributeError:
            return None

    def get_ibu(self):
        added_ibus = []
        try:
            for hop in self.recipe.hops.all():
                if hop.use in ["BOIL", "AROMA", "FIRST WORT", "WHIRLPOOL"]:
                    if hop.amount.g > 0 and hop.time > 0 and hop.alpha_acids > 0:
                        added_ibus.append(
                            functions.calculate_ibu_tinseth(
                                og=self.initial_gravity.sg,
                                time=float(hop.time),
                                type="PELLETS",
                                alpha=float(hop.alpha_acids),
                                weight=hop.amount.g,
                                volume=self.wort_volume.l + self.boil_loss.l,
                            )
                        )
        except AttributeError:
            return None
        return sum(added_ibus)

    def get_abv(self):
        try:
            return functions.get_abv(self.initial_gravity.sg, self.end_gravity.sg)
        except AttributeError:
            return None

    def get_attenuation(self):
        try:
            return functions.get_attenuation(self.initial_gravity.sg, self.end_gravity.sg)
        except AttributeError:
            return None

    def get_calories(self):
        try:
            return functions.get_beer_calories(self.initial_gravity.sg, self.end_gravity.sg)
        except AttributeError:
            return None

    @staticmethod
    def get_fields_by_stage(stage):
        fields = ["stage"]  # Must always be present
        if stage == "INIT":
            fields.extend(["recipe"])
        elif stage == "MASHING":
            fields.extend(
                [
                    "name",
                    "batch_number",
                    "brewing_day",
                    "grain_temperature",
                    "sparging_temperature",
                ]
            )
        elif stage == "BOIL":
            fields.extend(["gravity_before_boil"])
        elif stage == "PRIMARY_FERMENTATION":
            fields.extend(
                [
                    "initial_gravity",
                    "wort_volume",
                    "boil_loss",
                    "primary_fermentation_temperature",
                    "primary_fermentation_start_day",
                ]
            )
        elif stage == "SECONDARY_FERMENTATION":
            fields.extend(
                [
                    "post_primary_gravity",
                    "secondary_fermentation_start_day",
                    "dry_hops_start_day",
                ]
            )
        elif stage == "PACKAGING":
            fields.extend(
                [
                    "packaging_date",
                    "end_gravity",
                    "beer_volume",
                    "carbonation_type",
                    "carbonation_level",
                    "sugar_type",
                    "priming_temperature"
                ]
            )
        return fields

    def get_ndays_since_brewing(self):
        today = datetime.datetime.now().date()
        if self.primary_fermentation_start_day is not None:
            ndays = (today - self.primary_fermentation_start_day).days
            return ndays
        else:
            return 0
        

brivo/templates/brewery/batch/batch.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load brew_tags %}
{% load i18n %}

{% block title %}{{ batch.name }}{% endblock %}

{% block content %}
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog mt-5 modal-lg" role="document">
    <div class="modal-content"></div>
  </div>
</div>
{% if batch %}
  <div class="row mb-5">
        <!-- Breadcrumbs-->
        <ol id="breadcrumb">
            <li id="step-{{stages.1|lower}}"><a href="#">1. {% trans "Mashing" %}</a></li>
            <li id="step-{{stages.2|lower}}" class=""><a href="#">2. {% trans "Boiling" %}</a></li>
            <li id="step-{{stages.3|lower}}" class=""><a href="#">3. {% trans "Primary Fermentation" %}</a></li>
            <li id="step-{{stages.4|lower}}" class=""><a href="#">4. {% trans "Secondary Fermentation" %}</a></li>
            <li id="step-{{stages.5|lower}}"><a href="#">5. {% trans "Packaging" %}</a></li>
        </ol>
  </div>
{% endif %}

{% if batch %}
  <div class="row mb-5 pl-4">

    <h2>
      <button type="button" class="mr-1 bs-modal read-recipe btn btn-sm btn-default btn-dark" data-form-url="{% url 'brewery:recipe-detail' batch.recipe.pk %}">
        <span class="fa fa-eye"></span>
    </button>
    {% blocktrans with name=batch.name number=batch.batch_number recipe_name=batch.recipe.name %}
      Batch "{{name}}" no. {{number}} based on "{{recipe_name}}" recipe
    {% endblocktrans %}
  </h2>
  </div>
{% endif %}

  {% if batch.stage == "INIT" or batch is None %}
  <form class="form-horizontal" method="post" action="{% url 'brewery:batch-create' %}">
  {% else %}

  <form class="form-horizontal" method="post" action="{% url 'brewery:batch-update' batch.pk %}">
  {% endif %}
    {% csrf_token %}
    {% crispy form %}
  </form>


<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
$(document).ready(function() {

  $(".bs-modal").each(function () {
      $(this).modalForm({formURL: $(this).data("form-url")});
  });
  $( function() {
    $("#id_brewing_day" ).datepicker({
      dateFormat: "yy-mm-dd"
    });
    $("#id_primary_fermentation_start_day" ).datepicker({
      dateFormat: "yy-mm-dd"
    });
    $("#id_secondary_fermentation_start_day" ).datepicker({
      dateFormat: "yy-mm-dd"
    });
    $("#id_packaging_date" ).datepicker({
      dateFormat: "yy-mm-dd"
    });
    $("#id_dry_hops_start_day" ).datepicker({
      dateFormat: "yy-mm-dd"
    });

  });
  {% if batch %}
    {% for stage in stages %}
      {% if stage == batch.stage %}
        $("#step-{{stage|lower}}").find("a").addClass("active");
      {% elif forloop.counter <= stage_index %}
        $("#step-{{stage|lower}}").find("a").addClass("done");
      {% else %}
        $("#step-{{stage|lower}}").find("a").addClass("notdone");
      {% endif %}
    {% endfor %}
  {% endif %}

  function toggle_refermentation() {
    if ($("#id_carbonation_type").find(":selected").text() == "Refermentation") {
      $(".refermentation-fields").slideDown();
      $("#id_sugar_type").prop('required', true);
      $("#id_priming_temperature_0").prop('required', true);
    }
    else {
      $(".refermentation-fields").slideUp();
      $("#id_sugar_type").prop('required', false);
      $("#id_priming_temperature_0").prop('required', false);
    }
  }
  function check_priming_params() {
    if ($("#id_carbonation_type").find(":selected").text() == "Refermentation") {
      $.ajax({
        type: "POST",
        headers: { "X-CSRFToken": "{{ csrf_token }}" }, 
        url: '/api/brewery/calc/priming/',
        data: {
          "priming_temperature": $("#id_priming_temperature_0").val() + " {{temp_units.0}}",
          "beer_volume": $("#id_beer_volume_0").val() + " {{volume.0}}",
          "carbonation_level": $("#id_carbonation_level").val(),
          "sugar_type": $("#id_sugar_type").find(":selected").val(),
          "original_gravity": "{{ batch.initial_gravity|get_obj_attr:gravity_units.0|floatformat }} {{gravity_units.0}}"
        },
        dataType: 'json',
        success: function (data) {
          $("#priming_sugar_info_span").text(parseFloat(data["sugar_amount"].split(" ")[0]).toFixed(1));
          $("#priming_water_info_span").text(parseFloat(data["water_volume"].split(" ")[0]).toFixed(3));
        },
        error: function (data) {
          $("#priming_sugar_info_span").text("---");
          $("#priming_water_info_span").text("---");
        }
      });
    }
  }
  $("#id_carbonation_type").change(function(){
    toggle_refermentation();
  });
  $("#id_carbonation_type,#id_sugar_type,#id_priming_temperature_0,#id_carbonation_level,#id_beer_volume_0").change(function(){
    check_priming_params();
  });
  toggle_refermentation();
  check_priming_params();
});
</script>
{% endblock %}

brivo/templates/brewery/batch/delete.html
{% load static %}
{% load widget_tweaks %}
{% load i18n %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{% trans "Delete Batch" %}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">
    {% trans "Are you sure you want to delete batch with name" %}
      <strong>{{ batch.name }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">{% trans "Delete" %}</button>
  </div>

</form>
{% endblock content %}

brivo/templates/brewery/batch/fermentation_check.html
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load i18n %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{% trans "Add Fermentation Check" %}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    {{ form.sample_day|as_crispy_field }}
    {{ form.gravity|as_crispy_field }}
    {{ form.beer_temperature|as_crispy_field }}
    {{ form.ambient_temperature|as_crispy_field }}
    {{ form.comment|as_crispy_field }}
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-primary">{% trans "Add" %}</button>
  </div>

</form>
<script>
$(document).ready(function() {
  $( function() {
    $("#id_sample_day" ).datepicker({
      dateFormat: "yy-mm-dd"
    });
  });
});
</script>
{% endblock content %}

brivo/templates/brewery/batch/fermentation_check_delete.html
{% load static %}
{% load widget_tweaks %}
{% load i18n %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{% trans "Delete Fermentation Check" %}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">{% trans "Are you sure you want to delete this fermentation check?" %}</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">{% trans "Delete" %}</button>
  </div>

</form>
{% endblock content %}

brivo/templates/brewery/batch/fermentation_check_update.html
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load i18n %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{% trans "Update Fermentation Check" %}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    {{ form.sample_day|as_crispy_field }}
    {{ form.gravity|as_crispy_field }}
    {{ form.beer_temperature|as_crispy_field }}
    {{ form.ambient_temperature|as_crispy_field }}
    {{ form.comment|as_crispy_field }}
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-primary">{% trans "Update" %}</button>
  </div>

</form>
<script>
$(document).ready(function() {
  $( function() {
    $("#id_sample_day" ).datepicker({
      dateFormat: "yy-mm-dd"
    });
  });
});
</script>
{% endblock content %}

brivo/templates/brewery/batch/import.html
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}

<form method="post" action="{% url 'brewery:batch-import' %}" enctype="multipart/form-data">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{% trans "Import Batch" %}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
      {{form|crispy}}
  </div>

  <div class="modal-footer">
    <button type="submit" id="import-btn" class="btn btn-primary">{% trans "Import" %}</button>
  </div>

</form>
{% endblock content %}