brivo/brewery/urls.py
from django.urls import path

from . import views

app_name = "brewery"
urlpatterns = [
    # Fermentables
    path('fermentable', views.FermentableListView.as_view(),
         name='fermentable-list'),
    path('fermentable/create', views.FermentableCreateView.as_view(),
         name='fermentable-create'),
    path('fermentable/<int:pk>', views.FermentableDetailView.as_view(),
         name='fermentable-detail'),
    path('fermentable/<int:pk>/update', views.FermentableUpdateView.as_view(),
         name='fermentable-update'),
    path('fermentable/<int:pk>/delete', views.FermentableDeleteView.as_view(),
         name='fermentable-delete'),
    path(
        r'fermentable/autocomplete',
        views.FermentableAutocomplete.as_view(),
        name='fermentable-autocomplete',
    ),

    # Hops
    path('hop', views.HopListView.as_view(),
         name='hop-list'),
    path('hop/create', views.HopCreateView.as_view(),
         name='hop-create'),
    path('hop/<int:pk>', views.HopDetailView.as_view(),
         name='hop-detail'),
    path('hop/<int:pk>/update', views.HopUpdateView.as_view(),
         name='hop-update'),
    path('hop/<int:pk>/delete', views.HopDeleteView.as_view(),
         name='hop-delete'),
    path(
        r'hop/autocomplete',
        views.HopAutocomplete.as_view(),
        name='hop-autocomplete',
    ),

    # Yeasts
    path('yeast', views.YeastListView.as_view(),
         name='yeast-list'),
    path('yeast/create', views.YeastCreateView.as_view(),
         name='yeast-create'),
    path('yeast/<int:pk>', views.YeastDetailView.as_view(),
         name='yeast-detail'),
    path('yeast/<int:pk>/update', views.YeastUpdateView.as_view(),
         name='yeast-update'),
    path('yeast/<int:pk>/delete', views.YeastDeleteView.as_view(),
         name='yeast-delete'),
    path(
        r'yeast/autocomplete',
        views.YeastAutocomplete.as_view(),
        name='yeast-autocomplete',
    ),

    # Extras
    path('extra', views.ExtraListView.as_view(),
         name='extra-list'),
    path('extra/create', views.ExtraCreateView.as_view(),
         name='extra-create'),
    path('extra/<int:pk>', views.ExtraDetailView.as_view(),
         name='extra-detail'),
    path('extra/<int:pk>/update', views.ExtraUpdateView.as_view(),
         name='extra-update'),
    path('extra/<int:pk>/delete', views.ExtraDeleteView.as_view(),
         name='extra-delete'),
    path(
        r'extra/autocomplete',
        views.ExtraAutocomplete.as_view(),
        name='extra-autocomplete',
    ),

    # Styles
    path('style', views.StyleListView.as_view(),
         name='style-list'),
    path('style/create', views.StyleCreateView.as_view(),
         name='style-create'),
    path('style/<int:pk>', views.StyleDetailView.as_view(),
         name='style-detail'),
    path('style/<int:pk>/update', views.StyleUpdateView.as_view(),
         name='style-update'),
    path('style/<int:pk>/delete', views.StyleDeleteView.as_view(),
         name='style-delete'),
    path('style/<int:pk>/info', views.StyleInfoView.as_view(),
         name='style-info'),


    # Recipes
    path('recipe', views.RecipeListView.as_view(),
         name='recipe-list'),
    path('recipe/create', views.RecipeCreateView.as_view(),
         name='recipe-create'),
    path('recipe/<int:pk>', views.RecipeDetailView.as_view(),
         name='recipe-detail'),
    path('recipe/<int:pk>/print', views.RecipePrintView.as_view(),
         name='recipe-print'),
    path('recipe/<int:pk>/update', views.RecipeUpdateView.as_view(),
         name='recipe-update'),
    path('recipe/<int:pk>/delete', views.RecipeDeleteView.as_view(),
         name='recipe-delete'),
    path(
        r'recipe/info',
        views.get_recipe_data,
        name='recipe-info',
    ),
    path('recipe/import', views.RecipeImportView.as_view(),
         name='recipe-import'),

    # Batches
    path('batch', views.BatchListView.as_view(),
         name='batch-list'),
    path('batch/<int:pk>', views.BatchDetailView.as_view(),
         name='batch-detail'),
    path('batch/create', views.BatchView.as_view(),
         name='batch-create'),
    path('batch/<int:pk>/update', views.BatchView.as_view(),
         name='batch-update'),
    path('batch/<int:pk>/delete', views.BatchDeleteView.as_view(),
         name='batch-delete'),
    path('batch/import', views.BatchImportView.as_view(),
         name='batch-import'),
    path('batch/<int:batch_pk>/fermentation_check', views.FermentationCheckCreateView.as_view(),
         name='batch-fermentation_check-create'),
    path('batch/<int:batch_pk>/fermentation_check/<int:pk>/update', views.FermentationCheckUpdateView.as_view(),
         name='batch-fermentation_check-update'),
    path('batch/<int:batch_pk>/fermentation_check/<int:pk>/delete', views.FermentationCheckDeleteView.as_view(),
         name='batch-fermentation_check-delete'),
]

brivo/users/urls.py
from django.urls import path
from django.views import defaults as default_views

from brivo.users.views import (
    user_redirect_view,
    user_settings_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("<str:username>/", view=user_settings_view, name="settings"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.utils import translation
from django.urls import include, path, re_path
from django.conf.urls.i18n import i18n_patterns
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from brivo.users.api.views import CustomLogoutView

def set_language_from_url(request, user_language):
    translation.activate(user_language)
    request.session[translation.LANGUAGE_SESSION_KEY] = user_language
    return redirect(request.META.get('HTTP_REFERER'))

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management

    re_path(r'^celery-progress/', include('celery_progress.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router", namespace="api")),
    path("api/auth/logout/", CustomLogoutView.as_view()),
    path('api/auth/', include('dj_rest_auth.urls')),
    path('api/auth/registration/', include('dj_rest_auth.registration.urls')),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
        path(r'/set_language/(?P<user_language>\w+)/$', set_language_from_url, name="set_language_from_url"),
        path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
        path(
            "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
        ),
        path("users/", include("brivo.users.urls", namespace="users")),
        path("brewery/", include("brivo.brewery.urls", namespace="brewery")),
        path("accounts/email/", default_views.page_not_found, name="account_email", kwargs={"exception": Exception("Page not Found")},),
        path("accounts/", include("allauth.urls")),
    )


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

brivo/brewery/models/inventory.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from brivo.brewery.models import BaseModel

__all__ = ("Inventory",)

class Inventory(models.Model):
    user = models.OneToOneField("users.User", verbose_name=_("brewery.User"), on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.user.username} Inventory"

brivo/users/forms.py
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.safestring import mark_safe
from string import Template
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from allauth.account.forms import SignupForm

from brivo.users.models import (
    GENERAL_UNITS,
    GRAVITY_UNITS,
    UserProfile,
    UserBrewery)


User = get_user_model()


class AdminUserCreationForm(admin_forms.UserCreationForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)


    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ('email', 'username')
        error_messages = {
            "email": {"unique": _("This email has already been registered.")},
            "username": {"unique": _("This username has already been taken.")},
        }

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        profile = UserProfile.objects.create(user=user).save()
        brewery_profile = UserBrewery.objects.create(user=user).save()
        if commit:
            user.save()
        return user


class AdminUserChangeForm(admin_forms.UserChangeForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta(admin_forms.UserChangeForm.Meta):
        model = User
        fields = ('username', 'email', 'password', 'is_active', 'is_staff')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class BrivoSignupForm(SignupForm):

    general_units = forms.ChoiceField(choices=GENERAL_UNITS, required=False)
    gravity_units = forms.ChoiceField(choices=GRAVITY_UNITS, required=False)

    # Override the init method
    def __init__(self, *args, **kwargs):
        # Call the init of the parent class
        super().__init__(*args, **kwargs)

    # Put in custom signup logic
    def custom_signup(self, request, user):
        print("Setting data")
        user.profile = UserProfile.objects.create(user=user)
        user.profile.general_units = self.cleaned_data["general_units"]
        user.profile.gravity_units = self.cleaned_data["gravity_units"]
        user.brewery_profile = UserBrewery.objects.create(user=user)
        user.brewery_profile.save()
        user.profile.save()
        user.save()


class ImagePreviewWidget(forms.widgets.FileInput):
    def render(self, name, value, attrs=None, **kwargs):
        input_html = super().render(name, value, attrs=None, **kwargs)
        if value:
            img_html = mark_safe(f'<br><br><img style="width: 200px; height: 200px;" class="img-thumbnail" src="/media/{value}"/>')
            return f'{img_html}{input_html}'
        else:
            return input_html


class UserForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """

    class Meta:
        model = User
        fields = ('username', 'email',)


class UserProfileForm(forms.ModelForm):
    image = forms.ImageField(widget=ImagePreviewWidget)
    class Meta:
        model = UserProfile
        fields = (
            "image",
            "general_units",
            "temperature_units",
            "gravity_units",
            "color_units",
        )

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = False


class UserBreweryForm(forms.ModelForm):
    image = forms.ImageField(widget=ImagePreviewWidget)
    class Meta:
        model = UserBrewery
        fields = (
            "image",
            "name",
            "external_link",
            "number_of_batches"
        )

    def __init__(self, *args, **kwargs):
        super(UserBreweryForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = False

brivo/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet
from rest_framework.permissions import IsAuthenticated
from dj_rest_auth.views import LogoutView

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)


class CustomLogoutView(LogoutView):
    permission_classes = (IsAuthenticated,)

brivo/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.base import ContextMixin, TemplateResponseMixin
from django.views.generic.edit import ProcessFormView
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.http.response import HttpResponseRedirect
from django.http import HttpResponseForbidden
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from brivo.users.models import UserProfile, UserBrewery
from brivo.users import forms

User = get_user_model()

def user_settings_view(request, username):
    if not request.user.is_authenticated:
        return render(request, "403.html")
    if username != request.user.username:
        return render(request, "404.html")
    user = request.user
    user_profile = user.profile
    user_brewery = user.brewery_profile
    user_form = forms.UserForm(instance=request.user)
    

    if request.method == "POST":
        if 'profile_form' in request.POST:
            profile_form = forms.UserProfileForm(request.POST, request.FILES, instance=user.profile)
            if profile_form.is_valid():
                profile_form.save()

        if 'user_form' in request.POST:
            user_form = forms.UserForm(request.POST, instance=request.user)
            if user_form.is_valid():
                user_form.save()

        if 'brewery_form' in request.POST:
            brewery_form = forms.UserBreweryForm(request.POST, request.FILES, instance=user.brewery_profile)
            if brewery_form.is_valid():
                brewery_form.save()

    if user_profile:
        profile_form = forms.UserProfileForm(instance=user_profile)
    else:
        profile_form = forms.UserProfileForm()
    if user_brewery:
        brewery_form = forms.UserBreweryForm(instance=user_brewery)
    else:
        brewery_form = forms.UserBreweryForm()
    return render(request, 'users/settings.html', {
        'profile_form': profile_form,
        'user_form': user_form,
        'brewery_form': brewery_form
    })


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:settings", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

brivo/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Brivo{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Open Source Brewery App">
    <meta name="author" content="Rafal Gumienny">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="{% static 'js/html5shiv.min.js' %}"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.png' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script defer src="{% static 'js/popper.min.js' %}"></script>
      <script defer src="{% static 'js/bootstrap.min.js' %}"></script>
      <script defer src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
      <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script defer src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/Logo-flat.png' %}" alt="Logo" style="height:30px;"> </a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {% trans "Ingredients" %}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'brewery:fermentable-list' %}">{% trans "Fermentables" %}</a>
                  <a class="dropdown-item" href="{% url 'brewery:hop-list' %}">{% trans "Hops" %}</a>
                  <a class="dropdown-item" href="{% url 'brewery:yeast-list' %}">{% trans "Yeasts" %}</a>
                  <a class="dropdown-item" href="{% url 'brewery:extra-list' %}">{% trans "Extras" %}</a>
                </div>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'brewery:style-list' %}">{% trans "Styles" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'brewery:recipe-list' %}">{% trans "Recipes" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'brewery:batch-list' %}">{% trans "Brewlog" %}</a>
            </li>
            {% endif %}
          </ul>

          <ul class="navbar-nav ml-auto">

            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            
              <li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownLanguage" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false"><i
                              class="fas fa-globe"></i> {{LANGUAGE_CODE|title}}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownLanguage">
                  {% for language in languages %}
                    <form name="language_{{language.code}}" action="{% url 'set_language' %}" method="post">{% csrf_token %}
                      <input name="next" type="hidden" value="{{ redirect_to }}" />
                      <input name="language" type="hidden" value="{{language.code}}" />
                      <a class="dropdown-item" href="javascript:document.language_{{language.code}}.submit()">{{ language.name_local|title }} ({{ language.code|title }})</a>
                    </form>
                  {% endfor %}
                </div>                    
              </li>

              {% if user.is_authenticated %}
                  <li class="nav-item dropdown active">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false"><i
                              class="fas fa-user-alt"></i> {{ request.user.username }}
                      </a>

                      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                          <a class="dropdown-item" href="{% url 'users:settings' request.user.username  %}"><i
                                  class="fas fa-user-cog fa-fw"></i> {% trans 'Settings' %}</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="{% url 'account_logout' %}"><i
                                  class="fas fa-sign-out-alt fa-fw"></i> {% trans 'Log out' %}</a>
                      </div>
                  </li>
              {% else %}
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'account_signup' %}">{% trans 'Sign up' %} <i
                              class="fas fa-user-plus"></i></a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'account_login' %}">{% trans 'Sign in' %} <i
                              class="fas fa-sign-in-alt"></i></a>
                  </li>
              {% endif %}
          </ul>



        </div>
      </nav>

    </div>

    <div id="main_container" class="container" style="padding-bottom: 2.5rem;">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Fill me.</p>
      {% endblock content %}
    </div> <!-- /container -->

    <!-- Footer -->
    <footer class="footer">
      <!-- Copyright -->
      <div class="text-center py-3">© 2021 Copyright: Rafal Gumienny
      </div>
      <!-- Copyright -->

    </footer>
    <!-- Footer -->
    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {# Script tags with only code, no src (defer by default) #}
    {% endblock inline_javascript %}
  </body>
</html>
 

brivo/templates/pagination.html
{% load brew_tags %}
{% load i18n %}

<nav aria-label="navigation">
    <ul class="pagination justify-content-end mb-0">
{% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?{% param_replace page=page_obj.previous_page_number %}">
            <i class="fas fa-angle-left"></i>
            <span class="sr-only">{% trans "Previous" %}</span>
        </a>
    </li>
{% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">
            <i class="fas fa-angle-left"></i>
            <span class="sr-only">{% trans "Previous" %}</span>
        </a>
    </li>
{% endif %}

{% for i in page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="page-item active">
        <a class="page-link" href="?{% param_replace page=i %}">{{ page_obj.number }}</a>
      </li>
    {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
    <li class="page-item">
        <a class="page-link" href="?{% param_replace page=i %}">{{ i }}</a>
      </li>
    {% endif %}
{% endfor %}

{% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
    <li><a class="page-link" href="?{% param_replace page=page_obj.number|add:'5' %}">&hellip;</a></li>
{% endif %}

{% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?{% param_replace page=page_obj.next_page_number %}">
          <i class="fas fa-angle-right"></i>
          <span class="sr-only">{% trans "Next" %}</span>
        </a>
      </li>
{% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">
            <i class="fas fa-angle-right"></i>
            <span class="sr-only">{% trans "Next" %}</span>
        </a>
    </li>
{% endif %}
</ul>
</nav>